### ISSUE TITLE
My Business Q&A API Client Library for Java is not released yet

### ISSUE THREAD

**Issue by vpriesner** [googleapis/google-api-java-client-services#11459] opened 2022-01-11 10:52 UTC
The respective README (https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-mybusinessqanda/v1/README.md) mentions the following maven dependency:

<dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-mybusinessqanda</artifactId>
      <version>v1-rev20211211-1.32.1</version>
</dependency>

The central maven repository does not feature this dependency yet, though.
Since all the other GMB API client libraries for Java have been released, this is surely a mistake.

**Comment by vpriesner** [comment] 2022-01-11 11:38
As a workaround, I'm currently trying to generate a jar file from the classes (https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-mybusinessqanda/v1/1.31.0/com/google/api/services/mybusinessqanda/v1) directly.

As I'm inspecting the classes, I'm wondering whether the client library can even work with class names like this:

![image](https://user-images.githubusercontent.com/58213334/148936073-2c8b9c26-26a9-431e-bc53-fbce99831346.png)

**Comment by lesv** [comment] 2022-01-24 19:44
I can confirm this.  It's not in Maven Central.

**Comment by lesv** [comment] 2022-01-24 19:46
I see a depreciation schedule for v1 of the API
https://developers.google.com/my-business/content/sunset-dates

**Comment by vpriesner** [comment] 2022-01-24 19:51
@lesv it's the other way around - v4.9 of the GMB API will be deprecated in favor of the new federated model that includes the Q&A API v1.

**Comment by lesv** [comment] 2022-01-24 19:52
There is a link for a [mailing list](https://docs.google.com/forms/d/e/1FAIpQLScsFulRVy5_Z969K0GBhpIhdYpN88I8TsMj229ViArhqod8Mw/viewform) that you probably should join.

@vpriesner I would also suggest you [contact support](https://developers.google.com/my-business/content/support). 


I see no api's published on Maven Central for this. @chingor13 / @danoscarmike  Any ideas?

**Comment by vpriesner** [comment] 2022-01-24 19:56
I have contacted the GMB API "support" multiple times, but I'm not getting responses beyond "the team is investigating the issue"...

**Comment by lesv** [comment] 2022-01-27 00:54
@vpriesner Apologies - it should take a few days.

It appears to be similar to [this](https://github.com/googleapis/google-api-php-client-services/pull/588) for PHP.

@vam-google I thought this might be yours, but it's probably ours.
@eaball35 FYI
@Neenu1995 in case you have an idea.

I'm going to assign to me unless Emily or Neenu can take it.

**Comment by vpriesner** [comment] 2022-01-28 08:33
@lesv @chingor13 @danoscarmike
So with the fix having been merged, what's the timeline for the Maven Central release?

**Comment by lesv** [comment] 2022-01-29 22:16
I also merged another fix since that - it also only fixed part of the problem.  I'll be talking with someone on Monday, hopefully this will get released on Tuesday

**Comment by lesv** [comment] 2022-01-31 21:38
My fix #11497 actually worked, but the update failed in a way that wasn't logged, nor were we notified.
@chingor13 pushed through an updated PR #11706 that is the actual fix, so it will be released when the cron job runs, most likely tomorrow at Noon PT.  (ie. expect to see things on Maven Central around 2pm PT tomorrow)

**Closed by lesv** 2022-01-31 21:38 UTC
Labels: type: bug, priority: p2

**Comment by lesv** [comment] 2022-01-31 22:25
Actually, it appears the job will run at Midnight PT tonight

**Comment by lesv** [comment] 2022-01-31 23:37
It published just now.
https://repo1.maven.org/maven2/com/google/apis/google-api-services-mybusinessqanda/
